:green_heart: Fix lighthouse ci

diff --git a/.github/workflows/lighthouse-ci.yml b/.github/workflows/lighthouse-ci.yml
--- a/.github/workflows/lighthouse-ci.yml
+++ b/.github/workflows/lighthouse-ci.yml
@@ -41,14 +41,13 @@ jobs:
         run: pnpm install
 
       - name: Build the site
-        run: pnpm build
+        run: pnpm build -- --webpack
 
       - name: Run Lighthouse CI
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
         run: |
-          npm install -g @lhci/cli
-          lhci autorun || echo "Fail to Run Lighthouse CI!"
+          nnpx @lhci/cli@latest autorun || echo "Fail to Run Lighthouse CI!"
 
       - name: Format lighthouse score
         id: format_lighthouse_score
